export const paises: { [key: string]: string } = {
  'Alemania': 'Alemania',
  'Anguila': 'Anguila',
  'Argentina': 'Argentina',
  'Australia': 'Australia',
  'Austria': 'Austria',
  'Azerbaiyán': 'Azerbaiyán',
  'Bahamas': 'Bahamas',
  'Bangladesh': 'Bangladesh',
  'Barbados': 'Barbados',
  'Bélgica': 'Bélgica',
  'Bermudas': 'Bermudas',
  'Brasil': 'Brasil',
  'Bulgaria': 'Bulgaria',
  'Camboya': 'Camboya',
  'Canadá': 'Canadá',
  'Chile': 'Chile',
  'China': 'China',
  'Chipre': 'Chipre',
  'Colombia': 'Colombia',
  'Corea del Sur': 'Corea del Sur',
  'Costa de Marfil': 'Costa de Marfil',
  'Costa Rica': 'Costa Rica',
  'Dinamarca': 'Dinamarca',
  'Emiratos Árabes Unidos': 'Emiratos Árabes Unidos',
  'Eslovaquia': 'Eslovaquia',
  'Eslovenia': 'Eslovenia',
  'España': 'España',
  'Estados Unidos de América': 'Estados Unidos de América',
  'Estonia': 'Estonia',
  'Filipinas': 'Filipinas',
  'Finlandia': 'Finlandia',
  'Francia': 'Francia',
  'Gabón': 'Gabón',
  'Georgia': 'Georgia',
  'Gibraltar': 'Gibraltar',
  'Grecia': 'Grecia',
  'Groenlandia': 'Groenlandia',
  'Guernsey': 'Guernsey',
  'Hong Kong': 'Hong Kong',
  'Hungría': 'Hungría',
  'India': 'India',
  'Indonesia': 'Indonesia',
  'Irlanda': 'Irlanda',
  'Isla de Man': 'Isla de Man',
  'Islandia': 'Islandia',
  'Islas Caimán': 'Islas Caimán',
  'Islas Vírgenes Británicas': 'Islas Vírgenes Británicas',
  'Israel': 'Israel',
  'Italia': 'Italia',
  'Japón': 'Japón',
  'Jersey': 'Jersey',
  'Jordania': 'Jordania',
  'Kazajstán': 'Kazajstán',
  'Kenia': 'Kenia',
  'Letonia': 'Letonia',
  'Liechtenstein': 'Liechtenstein',
  'Lituania': 'Lituania',
  'Luxemburgo': 'Luxemburgo',
  'Macao': 'Macao',
  'Malasia': 'Malasia',
  'Malta': 'Malta',
  'Marruecos': 'Marruecos',
  'Mauricio': 'Mauricio',
  'México': 'México',
  'Mónaco': 'Mónaco',
  'Mongolia': 'Mongolia',
  'Mozambique': 'Mozambique',
  'n/d': 'n/d',
  'Nigeria': 'Nigeria',
  'Noruega': 'Noruega',
  'Nueva Zelanda': 'Nueva Zelanda',
  'Países Bajos': 'Países Bajos',
  'Panamá': 'Panamá',
  'Papúa Nueva Guinea': 'Papúa Nueva Guinea',
  'Perú': 'Perú',
  'Polonia': 'Polonia',
  'Portugal': 'Portugal',
  'Reino Unido': 'Reino Unido',
  'República Checa': 'República Checa',
  'Reunión': 'Reunión',
  'Rusia': 'Rusia',
  'Senegal': 'Senegal',
  'Singapur': 'Singapur',
  'Sudáfrica': 'Sudáfrica',
  'Suecia': 'Suecia',
  'Suiza': 'Suiza',
  'Tailandia': 'Tailandia',
  'Taiwán': 'Taiwán',
  'Turquía': 'Turquía',
  'Ucrania': 'Ucrania',
  'Uruguay': 'Uruguay',
  'Vietnam': 'Vietnam'
};
